name: proffy
description: Versão do projeto da rocketseat feita com Flutter.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.0
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
